
//! Autogenerated weights for `pallet_accounting`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2023-04-05, STEPS: `50`, REPEAT: 20, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! HOSTNAME: `ubuntu-s-8vcpu-16gb-fra1-01`, CPU: `DO-Regular`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// ./target/release/totem-parachain-collator
// benchmark
// pallet
// --chain=dev
// --execution=wasm
// --wasm-execution=compiled
// --pallet=pallet_accounting
// --extrinsic=*
// --steps=50
// --repeat=20
// --json
// --output=./weights/pallet_accounting-new-test.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::Weight};
use frame_support::weights::constants::RocksDbWeight;
use sp_std::marker::PhantomData;

/// Weight functions needed for pallet_unit_of_account.
pub trait WeightInfo {
	fn set_accounting_ref_date() -> Weight;
	fn set_opening_balance() -> Weight;
	fn adjustment() -> Weight;
}

/// Weight functions for `pallet_accounting`.
pub struct TotemWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for TotemWeight<T> {
	// Storage: Accounting AccountingRefDate (r:1 w:1)
	fn set_accounting_ref_date() -> Weight {
		// Minimum execution time: 49_198 nanoseconds.
		Weight::from_ref_time(57_191_000)
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	// Storage: Accounting AccountingRefDate (r:1 w:0)
	// Storage: Accounting OpeningBalance (r:2 w:2)
	// Storage: Accounting BalanceByLedger (r:3 w:2)
	// Storage: RandomnessCollectiveFlip RandomMaterial (r:1 w:0)
	// Storage: Timestamp Now (r:1 w:0)
	// Storage: unknown [0x3a65787472696e7369635f696e646578] (r:1 w:0)
	// Storage: Accounting PostingNumber (r:1 w:1)
	// Storage: Accounting GlobalLedger (r:2 w:2)
	// Storage: Accounting PostingDetail (r:0 w:2)
	// Storage: Accounting OpeningBalanceDate (r:0 w:1)
	fn set_opening_balance() -> Weight {
		// Minimum execution time: 209_765 nanoseconds.
		Weight::from_ref_time(216_162_000)
			.saturating_add(T::DbWeight::get().reads(12))
			.saturating_add(T::DbWeight::get().writes(10))
	}
	// Storage: Accounting PostingNumber (r:1 w:0)
	// Storage: Accounting PostingDetail (r:1 w:1)
	// Storage: RandomnessCollectiveFlip RandomMaterial (r:1 w:0)
	// Storage: Timestamp Now (r:1 w:0)
	// Storage: unknown [0x3a65787472696e7369635f696e646578] (r:1 w:0)
	// Storage: Accounting BalanceByLedger (r:1 w:1)
	// Storage: Accounting GlobalLedger (r:1 w:1)
	fn adjustment() -> Weight {
		// Minimum execution time: 133_480 nanoseconds.
		Weight::from_ref_time(143_782_000)
			.saturating_add(T::DbWeight::get().reads(7))
			.saturating_add(T::DbWeight::get().writes(3))
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	fn set_accounting_ref_date() -> Weight {
		Weight::from_ref_time(57_191_000)
			.saturating_add(RocksDbWeight::get().reads(1))
			.saturating_add(RocksDbWeight::get().writes(1))
	}

	fn set_opening_balance() -> Weight {
		Weight::from_ref_time(216_162_000)
			.saturating_add(RocksDbWeight::get().reads(12))
			.saturating_add(RocksDbWeight::get().writes(10))
	}

	fn adjustment() -> Weight {
		Weight::from_ref_time(143_782_000)
			.saturating_add(RocksDbWeight::get().reads(7))
			.saturating_add(RocksDbWeight::get().writes(3))
	}
}
