
//! Autogenerated weights for `pallet_prefunding`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2023-05-31, STEPS: `50`, REPEAT: 20, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! HOSTNAME: `ubuntu-s-8vcpu-16gb-fra1-01`, CPU: `DO-Regular`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// ./target/release/totem-parachain-collator
// benchmark
// pallet
// --chain=dev
// --execution=wasm
// --wasm-execution=compiled
// --pallet=pallet_prefunding
// --extrinsic=*
// --steps=50
// --repeat=20
// --json
// --output=./weights/pallet_prefunding-new-test.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::Weight};
use frame_support::weights::constants::RocksDbWeight;
use sp_std::marker::PhantomData;

/// Weight functions needed for pallet_unit_of_account.
pub trait WeightInfo {
	fn prefund_someone() -> Weight;
	fn pay_prefunded_invoice() -> Weight;
	fn invoice_prefunded_order() -> Weight;
	fn cancel_prefunded_closed_order() -> Weight;
}

/// Weight functions for `pallet_prefunding`.
pub struct TotemWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for TotemWeight<T> {
	// Storage: RandomnessCollectiveFlip RandomMaterial (r:1 w:0)
	// Storage: Timestamp Now (r:1 w:0)
	// Storage: unknown [0x3a65787472696e7369635f696e646578] (r:1 w:0)
	// Storage: Prefunding ReferenceStatus (r:1 w:1)
	// Storage: Escrow Escrowed (r:1 w:1)
	// Storage: System Account (r:1 w:1)
	// Storage: Accounting PostingNumber (r:1 w:1)
	// Storage: Accounting BalanceByLedger (r:3 w:3)
	// Storage: Accounting GlobalLedger (r:3 w:3)
	// Storage: Prefunding OwnerPrefundingHashList (r:1 w:1)
	// Storage: Accounting PostingDetail (r:0 w:3)
	// Storage: Prefunding PrefundingHashOwner (r:0 w:1)
	// Storage: Prefunding Prefunding (r:0 w:1)
	fn prefund_someone() -> Weight {
		// Minimum execution time: 278_718 nanoseconds.
		Weight::from_ref_time(475_458_000)
			.saturating_add(T::DbWeight::get().reads(14))
			.saturating_add(T::DbWeight::get().writes(16))
	}
	// Storage: Prefunding PrefundingHashOwner (r:1 w:0)
	// Storage: Accounting PostingNumber (r:1 w:1)
	// Storage: Accounting BalanceByLedger (r:6 w:6)
	// Storage: Accounting GlobalLedger (r:6 w:6)
	// Storage: Accounting PostingDetail (r:0 w:6)
	// Storage: Prefunding ReferenceStatus (r:0 w:1)
	fn invoice_prefunded_order() -> Weight {
		// Minimum execution time: 355_091 nanoseconds.
		Weight::from_ref_time(371_744_000)
			.saturating_add(T::DbWeight::get().reads(14))
			.saturating_add(T::DbWeight::get().writes(20))
	}
	// Storage: Prefunding PrefundingHashOwner (r:1 w:1)
	// Storage: Prefunding Prefunding (r:1 w:1)
	// Storage: Accounting PostingNumber (r:1 w:1)
	// Storage: Accounting BalanceByLedger (r:10 w:10)
	// Storage: Accounting GlobalLedger (r:8 w:8)
	// Storage: Prefunding ReferenceStatus (r:1 w:1)
	// Storage: Escrow Escrowed (r:1 w:1)
	// Storage: System Account (r:2 w:2)
	// Storage: Prefunding OwnerPrefundingHashList (r:1 w:1)
	// Storage: RandomnessCollectiveFlip RandomMaterial (r:1 w:0)
	// Storage: Timestamp Now (r:1 w:0)
	// Storage: unknown [0x3a65787472696e7369635f696e646578] (r:1 w:0)
	// Storage: Accounting PostingDetail (r:0 w:11)
	fn pay_prefunded_invoice() -> Weight {
		// Minimum execution time: 835_422 nanoseconds.
		Weight::from_ref_time(853_014_000)
			.saturating_add(T::DbWeight::get().reads(29))
			.saturating_add(T::DbWeight::get().writes(37))
	}
	// Storage: Prefunding ReferenceStatus (r:1 w:1)
	// Storage: Prefunding PrefundingHashOwner (r:1 w:1)
	// Storage: Escrow Escrowed (r:1 w:1)
	// Storage: System Account (r:1 w:1)
	// Storage: Prefunding OwnerPrefundingHashList (r:1 w:1)
	// Storage: Prefunding Prefunding (r:0 w:1)
	fn cancel_prefunded_closed_order() -> Weight {
		// Minimum execution time: 298_195 nanoseconds.
		Weight::from_ref_time(323_918_000)
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(6))
	}
}

impl WeightInfo for () {
	fn prefund_someone() -> Weight {
		Weight::from_ref_time(475_458_000)
			.saturating_add(RocksDbWeight::get().reads(14))
			.saturating_add(RocksDbWeight::get().writes(16))
	}

	fn pay_prefunded_invoice() -> Weight {
		Weight::from_ref_time(371_744_000)
			.saturating_add(RocksDbWeight::get().reads(14))
			.saturating_add(RocksDbWeight::get().writes(20))
	}

	fn invoice_prefunded_order() -> Weight {
		Weight::from_ref_time(853_014_000)
			.saturating_add(RocksDbWeight::get().reads(29))
			.saturating_add(RocksDbWeight::get().writes(37))
	}

	fn cancel_prefunded_closed_order() -> Weight {
		Weight::from_ref_time(323_918_000)
			.saturating_add(RocksDbWeight::get().reads(5))
			.saturating_add(RocksDbWeight::get().writes(6))
	}
}
